---
hostname: op-ampere

users:
  - username: mattjmcnaughton
    is_sudo: true
    groups:
      - docker

btrfs:
  root_volume:
    - device_name: /dev/mapper/encrypted_disk
      fs_label: encrypted_btrfs
      mount_path: /mnt/encrypted_btrfs
  subvolumes:
    - root_volume_fs_label: encrypted_btrfs
      subvolume_name: "@home"
      mount_path: /home
    - root_volume_fs_label: encrypted_btrfs
      subvolume_name: "@data"
      mount_path: /mnt/data
