---
hostname: op-ampere

users:
  - username: mattjmcnaughton
    is_sudo: true
    groups:
      - docker

btrfs:
  root_volume:
    - device_name: /dev/mapper/encrypted_disk
      fs_label: encrypted_btrfs
      mount_path: /mnt/encrypted_btrfs
  subvolumes:
    - root_volume_fs_label: encrypted_btrfs
      subvolume_name: "@home"
      mount_path: /home
      mode: "0750"
      owner: mattjmcnaughton
      group: mattjmcnaughton
    - root_volume_fs_label: encrypted_btrfs
      subvolume_name: "@data"
      mount_path: /mnt/data
      mode: "0750"
      owner: mattjmcnaughton
      group: mattjmcnaughton
    - root_volume_fs_label: encrypted_btrfs
      subvolume_name: "@vm-docker-compose-data"
      mount_path: /mnt/vm-docker-compose-data
      mode: "0750"
      owner: mattjmcnaughton
      group: mattjmcnaughton
