---
all:
  children:
    servers:
      children:
        ec2:
          hosts:

        on-prem:
          hosts:
            op-ampere:
              ansible_host: op-ampere

        vm:
          hosts:
            vm-docker-compose:
              ansible_host: vm-docker-compose

    nvidia-gpu:
      hosts:

    docker-compose-tailscale-service:
      hosts:
        vm-docker-compose:

    open-webui:
      hosts:
        vm-docker-compose:

    local-ai:
      hosts:
        vm-docker-compose:
