---
all:
  children:
    servers:
      children:
        ec2:
          hosts:

        on-prem:
          hosts:
            op-ampere:
              ansible_host: op-ampere

        vm:
          hosts:
            vm-docker-compose:
              ansible_host: vm-docker-compose

    nvidia-gpu:
      hosts:
