---
all:
  children:
    servers:
      children:
        ec2:
          hosts:
            ec2-open-webui:
              ansible_host: ec2-open-webui

        on-prem:
          hosts:
            op-ampere:
              ansible_host: op-ampere

    nvidia-gpu:
      hosts:

    docker-compose-tailscale-service:
      hosts:
        ec2-open-webui:

    open-webui:
      hosts:
        ec2-open-webui:
