---
all:
  children:
    servers:
      children:
        ec2:
          hosts:

        on-prem:
          hosts:
            op-ampere:
              ansible_host: op-ampere

        vm:
          hosts:
            vm-docker-compose:
              ansible_host: vm-docker-compose

            vm-docker-compose-litellm:
              ansible_host: vm-docker-compose

            vm-docker-compose-open-webui:
              ansible_host: vm-docker-compose

            vm-docker-compose-mcpo:
              ansible_host: vm-docker-compose

            vm-docker-compose-librechat:
              ansible_host: vm-docker-compose

            vm-docker-compose-langfuse:
              ansible_host: vm-docker-compose

    nvidia-gpu:
      hosts:

    docker-compose-tailscale-service:
      hosts:
        vm-docker-compose-litellm:
        vm-docker-compose-open-webui:
        vm-docker-compose-mcpo:
        vm-docker-compose-librechat:
        vm-docker-compose-langfuse:

    litellm:
      hosts:
        vm-docker-compose-litellm:

    open-webui:
      hosts:
        vm-docker-compose-open-webui:

    mcpo:
      hosts:
        vm-docker-compose-mcpo:

    librechat:
      hosts:
        vm-docker-compose-librechat:

    langfuse:
      hosts:
        vm-docker-compose-langfuse:
