---
service_name: "immich"
container_port: "2283"

host_data_dir_owner: "mattjmcnaughton"

aws_secrets_manager_secret_names:
  - "homelab/api/tailscale-scope-auth-key"
  - "homelab/app/immich"

# TODO: Currently, these are on a shared btrfs subvolume. TBD if that's
# good/bad.
host_data_dirs:
  - path: /mnt/data/immich-postgres-data
    mode: "0700"  # required by postgres
    owner: "{{ host_data_dir_owner }}"
    group: "{{ host_data_dir_owner }}"
  - path: /mnt/data/immich-uploads-data
    mode: "0750"
    owner: "{{ host_data_dir_owner }}"
    group: "{{ host_data_dir_owner }}"
  - path: /mnt/data/immich-caddy-data
    mode: "0750"
    owner: "{{ host_data_dir_owner }}"
    group: "{{ host_data_dir_owner }}"
